apiVersion: /v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zooplus-image
  name: zooplus-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zooplus-image
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zooplus-image
    spec:
      containers:
        - image: localhost:8080/
          name: zooplus-image
          resources: {}
status: {}
